### ISSUE TITLE
How to distinguish between documentation and the commented out blocks of code?

### ISSUE THREAD

**Issue by ckald** [ckald/pyccoon#9]
Possible solutions:
1. Ignore. We can always say that the user should maintain the docs himself
2. Use Pygments language detector for comments? If detected language == overall file language, then it is not docs, but the code. Might be slow.
3. Use specific syntax for documentation comments? Like C/PHP do: `/**` and `**/`. E.g., in Python that could be `##`. I would hate to remember that
4. Parse only multiline comments as docs? Most editors I know comment out the blocks of code using the inline comments. This seems to be too verbose

**Comment by cryptonomicon314** [comment]
1) You shoudn't comment out blocks of code. Use it or delete it. If you want to keep it for the future, that's what version control is for.
2) If you want to keep commented out code in the docs, enclose it with markdown ticks so that it will be highlighted as code, but appear on the documentation panel.

For python, I don't think using a special syntax for documentation is a good idea, because there is already one, the docstrings. For other languages it might be a possibility (I'm thinking of Haskell's LANGUAGE pragmas, https://downloads.haskell.org/~ghc/7.2.2/docs/html/users_guide/pragmas.html). In Python you should definitely not parse only multiline comments as docs. "Multiline comments" in python are docstrings, which have a specific place in the language. Inline comments are there to document all the rest.

**Comment by ckald** [comment]
So, "do nothing" is a viable strategy and I'm not the only one to think like this. Ok
